server:
  port: 8081
var:
  dumb: ${MYENV}

spring:
  application:
    name: dakobed-s3
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/dakobedDB
    password: postgres
#    url: jdbc:postgresql://${DAKOBED}:5432/dakobed
    username: postgres
#    password: ${DAKOBED_PASSWORD}

#    url: jdbc:postgresql://${DAKOBED}:5432/dakobed
#    username: postgres
#    password: ${DAKOBED_PASSWORD}
    driver-class-name: org.postgresql.Driver
