server:
  port: 8080
spring:
  application:
    name: dakobed-s3
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres

    url: jdbc:postgresql://${DAKOBED}:5432/dakobed
    username: postgres
    password: ${DAKOBED_PASSWORD}

#    url: jdbc:postgresql://dakobed.cju35raiyeyw.us-west-2.rds.amazonaws.com
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver


app:
  awsServices:
    bucketName: dakobed
cloud:
  aws:
    region:
      static: 'null'
    stack:
      auto: false

