version: '2'
services:

  scraper:
    build: .
    container_name: scraper
    depends_on:
      - postgres
    networks:
      - scrapenetwork
    command: python3 runscript.py
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/dakobedDB
  postgres:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dakobedDB
    container_name: postgres
    networks:
      - scrapenetwork



networks:
  scrapenetwork:
