server:
  port: 8084

amazon.dynamodb.endpoint:
  http://localhost:8000/
amazon.aws.accessKey:

amazon.aws.secretKey:


spring:
  application:
    name: dakobed-prodocuts
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/dakobedDB
    driver-class-name: org.postgresql.Driver


