
server:
  port: 8080
spring:
  application:
    name: dakobed-s3
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

amazon.dynamodb.endpoint:
  http://localhost:8000/

amazon.aws.accessKey:
amazon.aws.secretKey:

app:
  awsServices:
    bucketName: dakobed
cloud:
  aws:
    region:
      static: 'null'
    stack:
      auto: false
